version = 1

exclude_patterns = [
  "assets/v86/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "browser",
    "jquery"
  ]
  globals = ["anime", "V86"]

[[analyzers]]
name = "shell"
enabled = false

[[analyzers]]
name = "css"
enabled = false
